# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import path_finding


class MouseTracker(QtCore.QObject):
    """ This class is for getting the position of the curosr on window
        """
    positionChanged = QtCore.pyqtSignal(QtCore.QPoint)

    def __init__(self, widget):
        super().__init__(widget)
        self._widget = widget
        self.widget.setMouseTracking(True)
        self.widget.installEventFilter(self)
        self.trac_mouse=False

    @property
    def widget(self):
        return self._widget

    def eventFilter(self, o, e):
        """ this part is to draw on the label"""
        if o is self.widget and e.type() == QtCore.QEvent.MouseButtonPress :
            self.trac_mouse = True
        if self.trac_mouse and e.type() == QtCore.QEvent.MouseMove:
            self.positionChanged.emit(e.pos())
        if e.type() == QtCore.QEvent.MouseButtonRelease :
            self.trac_mouse = False 

        return super().eventFilter(o, e)

class MainWindow(QtWidgets.QMainWindow):
    """ this class is created by Qt Designer
        but we apply some change to use the MouseTracker class"""
    def __init__(self):
        super().__init__()

    def setupUi(self):
        self.setObjectName("MainWindow")
        #self.resize(960, 960)
        self.setGeometry(200,50,1200,1100)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        #720x540
        self.label.setGeometry(QtCore.QRect(80, 10, 960, 960))

        self.label.setText("")
        self.qt_image=path_finding.My_Image(self.label.height(),
                                self.label.width())
        self.label.setPixmap(QtGui.QPixmap(self.qt_image.image))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")


        """Here we create an obect of the class Mousetracker"""
        tracker = MouseTracker(self.label)
        tracker.positionChanged.connect(self.on_positionChanged)
        self.label_position = QtWidgets.QLabel(
            self.label, alignment=QtCore.Qt.AlignCenter
        )
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 21))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuEdit_2 = QtWidgets.QMenu(self.menubar)
        self.menuEdit_2.setObjectName("menuEdit_2")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionStart = QtWidgets.QAction(self)
        self.actionStart.setObjectName("actionStart")
        self.actionAlgo1 = QtWidgets.QAction(self)
        self.actionAlgo1.setObjectName("actionAlgo1")
        self.menuEdit.addAction(self.actionStart)
        self.menuEdit_2.addAction(self.actionAlgo1)
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuEdit_2.menuAction())
        self.actionStart.triggered.connect(self.action_start)
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self,w):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuEdit_2.setTitle(_translate("MainWindow", "Edit"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionAlgo1.setText(_translate("MainWindow", "Algo1"))
    @QtCore.pyqtSlot(QtCore.QPoint)
    def on_positionChanged(self, pos):
        """get the postion of the cursor"""
        self.label_position.show()
        self.label_position.move(pos)
        self.qt_image.draw_wall(pos.y(),pos.x())
        self.label.setPixmap(QtGui.QPixmap(self.qt_image.image))

    def action_start(self):

        self.path_algorithmus=path_finding.Choice_of_Algorithm(self.qt_image,start=(0,0),end=(31,31))
      #  self.path_algorithmus._wall_in_frame()
       # self.path_algorithmus.using_aglo1()
        #print(self.path_algorithmus.solution)
        self.path_algorithmus.start_algorithm()
        self.label.setPixmap(QtGui.QPixmap(self.qt_image.image))
if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.setupUi()
    window.show()
    sys.exit(app.exec_())
